### ISSUE TITLE
Unable to use in project/package where "type": "module"

### ISSUE THREAD

**Issue by clintwood** [TimMikeladze/arango-migrate#55]
Great project but I'm having issues with using it in a project/package when `"type": "module"` is set in the `package.json`.
I get the following errors:
```js
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user42/Documents/ITDev/projects/proj123/config.migrate.js from /Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js not supported.
config.migrate.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename config.migrate.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/user42/Documents/ITDev/projects/proj123/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Function.n.validateConfigPath (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:3560)
    at Object.<anonymous> (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:14046) {
  code: 'ERR_REQUIRE_ESM'

// Using config: config.migrate.js
const { database } = require('@abc-lib/load-config').loadConfig();

module.exports = {
  dbConfig: {
    databaseName: database.database,
    url: database.host,
    auth: {
      username: database.user,
      password: database.password,
    },
  },
};
```
Also tried a config with `-C` after renaming the config to `config.migrate.cjs` but that produced other errors 
```js
/Users/user42/Documents/ITDev/projects/proj123/config.migrate.cjs:1
const { database } = require('@abc-lib/load-config').loadConfig();
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user42/Documents/ITDev/projects/proj123/node_modules/@abc-lib/load-config/lib/index.js from /Users/user42/Documents/ITDev/projects/proj123/config.migrate.cjs not supported.
Instead change the require of index.js in /Users/user42/Documents/ITDev/projects/proj123/config.migrate.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/user42/Documents/ITDev/projects/proj123/config.migrate.cjs:1:22)
    at Function.n.validateConfigPath (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:3560)
    at Object.<anonymous> (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:14046) {
  code: 'ERR_REQUIRE_ESM'
}

// Using config: config.migrate.cjs
const { database } = require('@abc-lib/load-config').loadConfig();

module.exports = {
  dbConfig: {
    databaseName: database.database,
    url: database.host,
    auth: {
      username: database.user,
      password: database.password,
    },
  },
};
```
And also tried using ESM in the config but got these errors:
```js
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user42/Documents/ITDev/projects/proj123/config.migrate.js from /Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js not supported.
Instead change the require of config.migrate.js in /Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Function.n.validateConfigPath (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:3560)
    at Object.<anonymous> (/Users/user42/Documents/ITDev/projects/proj123/node_modules/arango-migrate/dist/cli.js:2:14046) {
  code: 'ERR_REQUIRE_ESM'
}

// Using // config.migrate.js
import { loadConfig } from '@awt-lib/load-config';

const { database } = loadConfig();

export default {
  dbConfig: {
    databaseName: database.database,
    url: database.host,
    auth: {
      username: database.user,
      password: database.password,
    },
  },
};
```
Would be great to use this but I cannot see how to work around this.

**Comment by TimMikeladze** [comment]
I'm also able to reproduce this by adding `"type": "module"` to the `package.json` file in the example repository https://github.com/TimMikeladze/arango-migrate-example.

Thanks for opening this issue, I will investigate and get back to you.

**Comment by clintwood** [comment]
Awesome, thank you!

**Comment by TimMikeladze** [comment]
@clintwood Hi, a new version of the package has been published which fixes this issue. You can check  out a functioning example in which the `package.json` file contains the `"type": "module"` here: 
https://github.com/TimMikeladze/arango-migrate-example. 

Let me know if there are any more problems. 

P.S. Sorry it took so long to get this done. I got severely side tracked and am just coming back to this project now.
